spring:
   datasource:
      url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root

   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
   secret: mimacom_2020*
   expiration: 600